//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XEXDecompiler3.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XEXDecompiler3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die b;ba;blr;bctr;bl;bla;blrl;bctrl;bt;bta;btlr;btctr;btl;btla;btlrl;btctrl;bf;bfa;bflr;bfctr;bfl;bfla;bflrl;bfctrl;bdnz;bdnza;bdnzlr;bdnzl;bdnzla;bdnzlrl;bdnzt;bdnzta;bdnztlr;bdnztl;bdnztla;bdnztlrl;bdnzf;bdnzfa;bdnzflr;bdnzfl;bdnzfla;bdnzflrl;bdz;bdza;bdzlr;bdzl;bdzla;bdzlrl;bdzt;bdzta;bdztlr;bdztl;bdztla;bdztlrl;bdzf;bdzfa;bdzflr;bdzfl;bdzfla;bdzflrl;blt;blta;bltlr;bltctr;bltl;bltla;bltlrl;bltctrl;ble;blea;blelr;blectr;blel;blela;blelrl;blectrl;beq;beqa;beqlr;beqctr;beql;beqla;beqlrl;beqctrl;bge;bgea;bgelr;b [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string branch_opcodes {
            get {
                return ResourceManager.GetString("branch_opcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bl;bla;blrl;bctrl;btl;btla;btlrl;btctrl;bfl;bfla;bflrl;bfctrl;bdnzla;bdnzlrl;bdnztl;bdnztla;bdnztlrl;bdnzfl;bdnzfla;bdnzflrl;bdzl;bdzla;bdzlrl;bdztl;bdztla;bdztlrl;bdzfl;bdzfla;bdzflrl;bltl;bltla;bltlrl;bltctrl;blel;blela;blelrl;blectrl;beql;beqla;beqlrl;beqctrl;bgel;bgela;bgerl;bgectrl;bgttl;bgla;bgtlrl;bgtctrl;bnll;bnlla;bnllrl;bnlctrl;bnel;bnela;bnelrl;bnectrl;bngl;bngla;bnglrl;bngctrl;bsol;bsola;bsolrl;bsoctrl;bnsl;bnsla;bnslrl;bnsctrl;bunl;bunla;bunlrl;bunctrl;bnul;bnula;bnulrl;bnuctrl ähnelt.
        /// </summary>
        internal static string branch_returning_prefixes {
            get {
                return ResourceManager.GetString("branch_returning_prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die b;ba;blr;bctr;bl;bla;blrl;bctrl ähnelt.
        /// </summary>
        internal static string uncond_prefixes {
            get {
                return ResourceManager.GetString("uncond_prefixes", resourceCulture);
            }
        }
    }
}
